### PR TITLE
Added composer.json

### PR DESCRIPTION
**Pull request by nunovieira**
Added composer.json in order to publish the package in https://packagist.org/

### CODE REVIEW

**Comment by nunovieira** [comment]
Is it ok to publish this in https://packagist.org/?

**Comment by tm1000** [comment]
Sure. I think the autoloader needs to be redone though. But if you think it's ok I am fine with it being there.

**Comment by nunovieira** [comment]
I think it can be published and the improvements come later.
It should be published by an admin of this project, in order to set up the GitHub Service Hook to auto-update.

**Comment by tm1000** [comment]
Ok I can do that and manage it and maybe update a few things.

**Comment by tm1000** [comment]
Done!

https://packagist.org/packages/provisioner/provisioner

**Pull request merged**
